# This file is the custom resource for kustomize transformer
# Spec field is defined for custom scripts
# See ./base/krmfunc/ingress_patch.py for details
apiVersion: kustomize-ingress/v1alpha1
kind: IngressPatch
metadata:
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ./krmfunc/ingress_patch.py
  name: my-ingress
spec:
  hosts: 
  - name: app1.stg.example.com
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:ACCOUNTID:certificate/STAGING_ARN
